{{- if and .Values.rbac.create .Values.watchAllNamespaces -}}
apiVersion: {{ include "source-controller.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "source-controller.rbac.fullname" . }}:bucket-editor
  labels:
    {{- include "source-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - buckets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - buckets/status
    verbs:
      - get
{{- end }}
