{{- if and .Values.rbac.create (not .Values.watchAllNamespaces) -}}
apiVersion: {{ include "source-controller.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ include "source-controller.rbac.fullname" . }}:gitrepository-viewer
  labels:
    {{- include "source-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - gitrepositories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - gitrepositories/status
    verbs:
      - get
{{- end }}
