{{- if and .Values.rbac.create (not .Values.watchAllNamespaces) -}}
apiVersion: {{ include "source-controller.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ include "source-controller.rbac.fullname" . }}:helmrepository-editor
  labels:
    {{- include "source-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmrepositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmrepositories/status
    verbs:
      - get
{{- end }}
