{{- if and .Values.rbac.create .Values.watchAllNamespaces -}}
apiVersion: {{ include "source-controller.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "source-controller.rbac.fullname" . }}:helmchart-viewer
  labels:
    {{- include "source-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmcharts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmcharts/status
    verbs:
      - get
{{- end }}
